### ISSUE TITLE
The numbers in the profile have not changed.

### ISSUE THREAD

**Issue by Gigabait** [oliver-ni/poketwo#102]
**Describe the bug**
The numbers of the pokemon in the profile are not updated after trade.

**To Reproduce**
Just trade with other trainer.

**Expected behavior**
I expected them to be in sequence from 1 to max.

**Screenshots**
![image](https://user-images.githubusercontent.com/16218922/104189606-b7999a00-543c-11eb-86de-1972e2302505.png)

**Additional context**

**Comment by unknownking31** [comment]
I mean u could just p!reindex after trading

**Comment by unknownking31** [comment]
Idk exact reason why they dont update everytime u release or trade but i think its to prevent bot from overloading

**Comment by NathNathNathNath** [comment]
I concur that this isn't a bug, the "gaps" in the numbers are intentional. Or rather, it's an intentional decision *not* to fill in the gaps as you acquire new pokemon - the numbers always just increment.

In my opinion it would be confusing for newly caught/traded pokemon to be seemingly-randomly inserted into those gaps.

To make the gaps disappear, you can use the p!reindex command at any time. That will shift all of your pokemon down the list, while maintaining the actual order of the pokemon (which cannot be changed*)

- - - 
*Technically can be but it would require trading back and forth with another account in a targeted way

**Comment by Gigabait** [comment]
Uh, sorry, I didn't find the p!reindex command, thanks.
